config/routes.rb
Tangueros::Application.routes.draw do

  devise_for :users

  if Rails.env.development?
    get "/miv", to: "miv#index"
  end

  get '/sitemap' => "events#sitemap", :as => :sitemap
  
  resources :events, except: [:index, :edit] do
    collection do
      get "happening"
      get "upcoming"
      get "past"
      get "sitemap"
    end
  end

  root "events#index"

end

app/models/event.rb
#coding: utf-8

class Event < ActiveRecord::Base
  
  default_scope { select("*, events.next_starts_at::timestamptz AS next_starts_at, events.next_ends_at::timestamptz AS next_ends_at") }

  belongs_to :event_type
  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates_presence_of :user, :event_type, :name, :starts_at, :location

  geocoded_by :full_address
  after_validation :geocode
  
  before_create do
    self.permalink = self.name unless self.permalink.present?
  end

  def self.happening
    where("events.next_starts_at < now() AND events.next_ends_at > now() AND events.next_ends_at IS NOT NULL").order("events.next_starts_at DESC")
  end

  def self.upcoming
    where("events.next_starts_at >= now()").order("events.next_starts_at")
  end

  def self.past
    where("(events.next_ends_at IS NOT NULL AND events.next_ends_at < now()) OR (events.next_ends_at IS NULL AND events.next_starts_at < now())").order("events.next_starts_at DESC")
  end
  
  def to_param
    "#{self.id}-#{self.permalink.parameterize}"
  end

  def next_starts_at
    self.attributes["next_starts_at"].try(:localtime)
  end

  def next_ends_at
    self.attributes["next_ends_at"].try(:localtime)
  end

  def full_address
    return self.address if self.address && self.address.match(/Porto Alegre/i)
    "#{self.address} Porto Alegre".strip
  end

end

app/models/event_type.rb
class EventType < ActiveRecord::Base
  validates_uniqueness_of :name
  validates_presence_of :name
  has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  has_many :events

  before_create do
    self.name = self.email.match(/(.+)@/)[1] unless self.name.present?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :namespace, :add_headline_and_article!, :suppress_headline_and_article!, :add_headline_and_article?

  after_action :verify_authorized, unless: -> {devise_controller? || self.class == HighVoltage::PagesController}
  after_action :verify_policy_scoped, unless: -> {devise_controller? || self.class == HighVoltage::PagesController}
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # This will send the current_user to the view and instantiate UserDecorator
  before_action :current_user

  def add_headline_and_article?
    !@suppress_headline_and_article
  end

  def add_headline_and_article!
    @suppress_headline_and_article = false
  end

  def suppress_headline_and_article!
    @suppress_headline_and_article = true
  end

  def namespace
    names = self.class.to_s.split('::')
    return "null" if names.length < 2
    names[0..(names.length-2)].map(&:downcase).join('_')
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:account_update) << :image
  end

  def user_not_authorized(exception)
    policy_name = exception.policy.class.to_s.underscore
    flash[:error] = I18n.t "pundit.#{policy_name}.#{exception.query}", default: 'Você não possui as permissões necessárias para realizar esta ação.'
    redirect_to(request.referrer || root_path)
  end

end

app/controllers/events_controller.rb
#coding: utf-8

class EventsController < ApplicationController
  
  inherit_resources
  respond_to :html, :json, :xml
  custom_actions collection: %i[happening upcoming past sitemap]

  after_action :verify_authorized, except: %i[index happening upcoming past sitemap]
  after_action :verify_policy_scoped, only: %i[index happening upcoming past sitemap]
  before_action :authenticate_user!, only: %i[new]

  def index
    @events = policy_scope(Event)
    index! do |format|
      format.html do
        @happening = @events.happening.limit(3)
        @upcoming = @events.upcoming.limit(3)
        @past = @events.past.limit(3)
      end
    end
  end

  def show
    show! { authorize @event }
  end

  def new
    new! { authorize @event }
  end

  def create
    set_start_and_end_params!
    @event = Event.new(event_params)
    @event.user = current_user
    authorize @event
    create!(notice: "Evento criado com sucesso! Agora é só compartilhar :D")
  end

  def update
    set_start_and_end_params!
    authorize resource
    update!(notice: "Evento atualizado com sucesso :D")
  end

  def destroy
    authorize resource
    destroy!(notice: "Evento excluído com sucesso :D") { root_path }
  end

  def happening
    @events = policy_scope(Event).happening
    happening!
  end

  def upcoming
    @events = policy_scope(Event).upcoming
    upcoming!
  end

  def past
    @events = policy_scope(Event).past
    past!
  end

  def sitemap
    @events = policy_scope(Event)
    sitemap! do |format|
      format.xml do
        @happening = @events.happening
        @upcoming = @events.upcoming
        @past = @events.past
      end
    end
  end

  private

  def permitted_params
    params.permit(event: [:name, :event_type_id, :starts_at, :ends_at, :description, :location, :address, :image, :url, :weekly])
  end

  def event_params
    params.require(:event).permit(:name, :event_type_id, :starts_at, :ends_at, :description, :location, :address, :image, :url, :weekly)
  end

  def set_start_and_end_params!
    if params[:starts_at_date_submit].present? && params[:starts_at_time_submit].present? && !params[:event][:starts_at].present?
      params[:event][:starts_at] = "#{params[:starts_at_date_submit]} #{params[:starts_at_time_submit]}"
    end
    if params[:ends_at_date_submit].present? && params[:ends_at_time_submit].present? && !params[:event][:ends_at].present?
      params[:event][:ends_at] = "#{params[:ends_at_date_submit]} #{params[:ends_at_time_submit]}"
    end
  end

end

app/views/events/_event.html.slim
article.event
  a href=event_path(event) title=event.name
    .image= image_tag(event.image.url(:medium)) if event.image.present?
    .info
      h3= truncate event.name, length: 48
      time.start datetime=event.next_starts_at.iso8601
        = image_tag 'calendar.svg'
        - if event.weekly?
          = l(event.next_starts_at, format: :week).pluralize
          = ", "
          = l(event.next_starts_at, format: :time)
        - else
          = l event.next_starts_at, format: :medium
      .location
        = image_tag 'location.svg'
        span= event.location
      .type= image_tag "event_types/#{event.event_type.name.parameterize}.svg", alt: event.event_type.name, title: event.event_type.name

app/views/events/_form.html.slim
= form_for(@event) do |form|
  - if @event.errors.any?
    #error_explanation
      h3 = "#{pluralize(@event.errors.count, "erro impediu", "erros impediram")} que este evento fosse salvo:"
      ul
        - @event.errors.full_messages.each do |msg|
          li= msg
  = form.label :name
  = form.text_field :name
  = form.label :event_type_id
  = form.collection_select :event_type_id, EventType.order(:id), :id, :name, selected: @event.event_type_id
  = form.label :starts_at
  = text_field_tag :starts_at_date, (l(@event.starts_at.to_date) if @event.starts_at), class: "date", placeholder: "Data de início"
  = text_field_tag :starts_at_time, (l(@event.starts_at, format: :time) if @event.starts_at), class: "time", placeholder: "Hora de início"
  = form.label :location
  = form.text_field :location
  = form.submit

app/views/events/happening.html.slim
- content_for :title do
  = "Eventos acontecendo agora"
- content_for :url do
  = happening_events_url
- if @events.exists?
  section.events
    = render @events

app/views/events/index.html.slim
- suppress_headline_and_article!
- content_for :title do
  = "A agenda colaborativa do tango"
- content_for :url do
  = root_url
- content_for :meta_tags do
  meta name="description" content="Fique por dentro do que acontece no tango de Porto Alegre! Qualquer pessoa pode adicionar um evento de tango que aconteça em Porto Alegre. Desse jeito, todo mundo fica sabendo das milongas, práticas, shows, aulas, etc, da cidade. E o tango porto-alegrense só cresce!"
  meta name="keywords" content="Tango Porto Alegre acontece evento tango milongas práticas shows aulas cidade"
  meta property="og:title" content="A agenda colaborativa do tango"
  meta property="og:type" content="website"
  meta property="og:url" content=(root_url)
  meta property="og:image" content=="#{request.protocol}#{request.host_with_port}#{image_path("tango_facebook.png")}"
  meta property="og:description" content="Qualquer pessoa pode adicionar um evento de tango que aconteça em Porto Alegre. Desse jeito, todo mundo fica sabendo das milongas, práticas, shows, aulas, etc, da cidade. E o tango porto-alegrense só cresce!"
- if @happening.exists?
  section.events
    h2
      = "Acontecendo agora"
      = link_to "ver mais", happening_events_path, class: "mobile"
      = link_to "ver mais eventos acontecendo agora ￫", happening_events_path, class: "not_mobile"
    div= render @happening
  hr
- if @upcoming.exists?
  section.events
    h2
      = "Próximos eventos"
      = link_to "ver mais", upcoming_events_path, class: "mobile"
      = link_to "ver mais próximos eventos ￫", upcoming_events_path, class: "not_mobile"
    div= render @upcoming
  hr
- if @past.exists?
  section.events
    h2
      = "Últimos eventos"
      = link_to "ver mais", past_events_path, class: "mobile"
      = link_to "ver mais eventos que já aconteceram ￫", past_events_path, class: "not_mobile"
    div= render @past
section.new
  h2 Tá sabendo de algum evento que não tá aqui?
  = link_to 'Clique aqui para adicionar um evento', new_event_path, class: 'button'

app/views/events/new.html.slim
- content_for :title do
  = "Novo evento"
- content_for :url do
  = new_event_url
= render 'form'

app/views/events/past.html.slim
- content_for :title do
  = "Eventos que já aconteceram"
- content_for :url do
  = past_events_url
- if @events.exists?
  section.events
    = render @events

app/views/events/show.html.slim
- suppress_headline_and_article!
- content_for :title do
  = @event.name
- content_for :url do
  = event_url(@event)
- content_for :external_js do
  script src="//maps.google.com/maps/api/js?v=3.13&libraries=geometry&sensor=false" type="text/javascript"
  script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'
- content_for :meta_tags do
    meta name="author" content=@event.user.name
    meta name="description" content=@event.description
    meta name="keywords" content="#{@event.name} #{@event.description} Tango Porto Alegre"
    meta property="og:title" content=@event.name
    meta property="og:type" content="event"
    meta property="event:start_time" content=@event.next_starts_at
    - if @event.next_ends_at
      meta property="event:end_time" content=@event.next_ends_at
    meta property="event:location:latitude" content=@event.latitude
    meta property="event:location:longitude" content=@event.longitude
    meta property="og:url" content=event_url(@event)
    meta property="og:image" content=(@event.image.present? ? @event.image.url : "#{request.protocol}#{request.host_with_port}#{image_path("tango_facebook.png")}")
    meta property="og:description" content=@event.description
article id=dom_id(@event)
  header
    - if policy(@event).update? && !@event.complete_profile?
      section.tips
        h5 Dicas para deixar seu evento bonitão
        ol
          - @event.tips.each do |tip|
            li== tip
    .image
      - if @event.image.present?
        = link_to image_tag(@event.image.url, style: "margin-top: #{@event.margin}"), @event.image.url, target: :_blank
    h2= @event.name
    .type
      = image_tag "event_types/#{@event.event_type.name.parameterize}.svg", alt: @event.event_type.name, title: @event.event_type.name
      = @event.event_type.name
    .time
      time.start datetime=@event.next_starts_at.iso8601
        = image_tag 'calendar.svg'
        - if @event.weekly?
          = l(@event.next_starts_at, format: :week).pluralize
          = ", "
          = l(@event.next_starts_at, format: :time)
        - else
          = l @event.next_starts_at, format: :medium
      - if @event.next_ends_at.present?
        time.end datetime=@event.next_ends_at.iso8601
          - if @event.next_ends_at.to_date > @event.next_starts_at.to_date
            = "Até "
            = l @event.next_ends_at, format: :medium_short
          - else
            = "Até às "
            = l @event.next_ends_at, format: :time
  .where
    - if @event.latitude && @event.longitude
      #map data-latitude=@event.latitude data-longitude=@event.longitude
    = image_tag 'location.svg'
    = @event.location
    = " · #{@event.address}" if @event.address.present?
  p class=('editable' if policy(@event).update?) data-attribute="description" data-formtype="textarea" data-placeholder="Descrição do seu evento"= @event.description
  #description
  - if policy(@event).update?
    section.admin
      h4 Atualizar informações do evento
      .field#image
        = form_for(@event) do |form|
          = form.label :image
          = form.file_field :image
      .field
        = label_tag :name, Event.human_attribute_name(:name)
        span#name.editable data-attribute="name" data-placeholder="Nome do seu evento"= @event.name
      .field
        = label_tag :starts_at, Event.human_attribute_name(:starts_at)
        span#starts_at.editable data-attribute="starts_at" data-formtype="timestamp" data-placeholder="Início do evento"=("#{l(@event.starts_at.to_date)} #{l(@event.starts_at, format: :time)}" if @event.starts_at)
      .field
        = label_tag :ends_at, Event.human_attribute_name(:ends_at)
        span#ends_at.editable data-attribute="ends_at" data-formtype="timestamp" data-placeholder="Fim do evento"=("#{l(@event.ends_at.to_date)} #{l(@event.ends_at, format: :time)}" if @event.ends_at)
      .field
        = label_tag :location, Event.human_attribute_name(:location)
        span#location.editable data-attribute="location" data-placeholder="Local do seu evento"= @event.location
      .field
        = label_tag :address, Event.human_attribute_name(:address)
        span#address.editable data-attribute="address" data-placeholder="Rua do evento, nº XXX"= @event.address
      .field
        = label_tag :url, Event.human_attribute_name(:url)
        span#url.editable data-attribute="url" data-placeholder="http://www.site.do.seu.evento/"= @event.url
      .field
        = check_box_tag :weekly, "1", @event.weekly, :class => "editable", :"data-attribute" => "weekly", :"data-formtype" => "checkbox"
        = label_tag :weekly, Event.human_attribute_name(:weekly)
  .links
    - if @event.url.present?
      = link_to "Mais informações", @event.url, target: :_blank, class: "button"
    - if policy(@event).destroy?
      = link_to 'Excluir evento', @event, method: :delete, data: { confirm: 'Seu evento será excluído. Você está certo disso?' }, class: "button"

app/views/events/upcoming.html.slim
- content_for :title do
  = "Próximos eventos"
- content_for :url do
  = upcoming_events_url
- if @events.exists?
  section.events
    = render @events

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta name="robots" content="index, follow"
    meta name="viewport" content="initial-scale=1.0, width=device-width"
    - if content_for? :meta_tags
      / Page specific meta tags
      = yield :meta_tags
    - else
      / Meta tags for pages that don't have specific meta tags
      meta name="author" content="Daniel Weinmann"
      meta name="description" content=yield(:title)
      meta name="keywords" content="#{yield :title} Tangueros Porto Alegre"
      meta property="og:title" content=yield(:title)
      meta property="og:type" content="website"
      meta property="og:url" content=(content_for?(:url) ? yield(:url) : request.url)
      meta property="og:image" content=="#{request.protocol}#{request.host_with_port}#{image_path("tango_facebook.png")}"
      meta property="og:description" content=yield(:title)
    / Metatags for every page
    meta property="og:site_name" content="Tangueros Porto Alegre"
    meta property="fb:app_id" content=ENV['FACEBOOK_APP_ID']
    meta property="fb:admins" content=ENV['FACEBOOK_ADMINS']
    title= "#{"#{yield :title} · " if content_for?(:title)}Tangueros Porto Alegre"
    - if content_for? :external_js
      = yield :external_js
    link href='http://fonts.googleapis.com/css?family=Homenaje%7COpen+Sans:400,700' rel='stylesheet'
    = stylesheet_link_tag "application"
    link rel="shortcut icon" href==image_path('tango.png')
    javascript:
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-43352814-3', 'tangueros.me');
    = javascript_include_tag "application" 
    = csrf_meta_tags 
  body[data-namespace="#{namespace}" data-controller="#{controller_name}" data-action="#{action_name}" data-locale="#{I18n.locale}" data-facebook_app_id="#{ENV['FACEBOOK_APP_ID']}"]
    - if Rails.env.production?
      javascript:
        ga('send', 'pageview');
    div#fb-root
    #flash
      - for key, msg in flash
        - unless key == :timedout
          div class="#{key}" = msg
    #header_wrapper
      header
        = link_to :root do
          = image_tag 'tango.svg', alt: "Tangueros", title: "Tangueros"
          h1
            = "Tangueros "
            span Porto Alegre
        - if current_user
          .menu
            a.open href="#"
              = image_tag(current_user.thumbnail)
              = truncate current_user.name, length: 18
              span ▾
            nav
              = link_to "Adicionar evento", new_event_path
              = link_to "Meus dados", edit_user_registration_path
              hr
              = link_to "Sair", destroy_user_session_path, method: :delete
        - else
          nav.sign_in
            = link_to "Cadastre-se", new_user_registration_path
            = link_to "Login", new_user_session_path
    #content
      - if add_headline_and_article?
        article
          - if content_for?(:title)
            h2= yield :title
          = yield
      - else
        = yield
    footer
      section.user
        nav
          - if current_user
              = link_to "Meus dados", edit_user_registration_path
              = link_to "Sair", destroy_user_session_path, method: :delete
          - elsif namespace != "devise"
              = link_to "Cadastre-se", new_user_registration_path
              = link_to "Login", new_user_session_path
      section.social
        h5 Curta esta página no Facebook
        .fb-like data-href=(content_for?(:url) ? yield(:url) : request.url) data-width="320" data-show-faces="true" data-share="true"
      section.credits
        h5
          = "Feito com amor e "
          = link_to 'Open Source', page_path('credits')
          = " em 2014 ♥"

app/views/pages/credits.html.slim
- content_for :title do
  = "Créditos"
- content_for :url do
  = page_url('credits')
ul
  li
    = "Criado por "
    a href="http://fb.com/danielweinmann" target="_blank" Daniel Weinmann
    = " e publicado como código aberto no "
    a href="https://github.com/danielweinmann/tangueros" target="_blank" GitHub
    = " sob "
    a href="https://github.com/danielweinmann/tangueros/blob/master/MIT-LICENSE" target="_blank" licensa MIT
  li
    = "O ícone "
    a href="http://thenounproject.com/term/tango/343/" target="_blank" Tango
    = ", usado no cabeçalho do site, é de criação de "
    a href="http://www.thenounproject.com/edward" target="_blank" Edward Boatman
    = " e publicado originalmente no "
    a href="http://www.thenounproject.com" target="_blank" The Noun Project
    = " sob lincensa "
    a href="http://creativecommons.org/licenses/by/3.0/us/" target="_blank" Creative Commons – Attribution (CC BY 3.0)
  li
    = "O ícone "
    a href="http://thenounproject.com/term/calendar/404/" target="_blank" Calendar
    = ", usado no site, é de criação de "
    a href="http://www.thenounproject.com/edward" target="_blank" Edward Boatman
    = " e publicado originalmente no "
    a href="http://www.thenounproject.com" target="_blank" The Noun Project
    = " sob lincensa "
    a href="http://creativecommons.org/licenses/by/3.0/us/" target="_blank" Creative Commons – Attribution (CC BY 3.0)
  li
    = "O ícone "
    a href="http://thenounproject.com/term/record/16289/" target="_blank" Record
    = ", usado no site, é de criação de "
    a href="http://www.thenounproject.com/etrav689" target="_blank" Evan Travelstead
    = " e publicado originalmente no "
    a href="http://www.thenounproject.com" target="_blank" The Noun Project
    = " sob lincensa "
    a href="http://creativecommons.org/licenses/by/3.0/us/" target="_blank" Creative Commons – Attribution (CC BY 3.0)
  li
    = "O ícone "
    a href="http://thenounproject.com/term/tango/34355/" target="_blank" Tango
    = ", usado no site, é de criação de "
    a href="http://www.thenounproject.com/nav" target="_blank" Navie Naidu
    = " e publicado originalmente no "
    a href="http://www.thenounproject.com" target="_blank" The Noun Project
    = " sob lincensa "
    a href="http://creativecommons.org/licenses/by/3.0/us/" target="_blank" Creative Commons – Attribution (CC BY 3.0)
  li
    = "O ícone "
    a href="http://thenounproject.com/term/yoga/32810/" target="_blank" Yoga
    = ", usado no site, é de criação de "
    a href="http://www.thenounproject.com/blaisetsewell" target="_blank" Blaise Sewell
    = " e publicado originalmente no "
    a href="http://www.thenounproject.com" target="_blank" The Noun Project
    = " sob lincensa "
    a href="http://creativecommons.org/licenses/by/3.0/us/" target="_blank" Creative Commons – Attribution (CC BY 3.0)
  li
    = "O ícone "
    a href="http://thenounproject.com/term/tag/1319/" target="_blank" Tag
    = ", usado no site, é de criação de "
    a href="http://www.thenounproject.com/johncaserta" target="_blank" John Caserta
    = " e publicado originalmente no "
    a href="http://www.thenounproject.com" target="_blank" The Noun Project
    = " sob lincensa "
    a href="http://creativecommons.org/licenses/by/3.0/us/" target="_blank" Creative Commons – Attribution (CC BY 3.0)
  li
    = "O ícone "
    a href="http://thenounproject.com/term/user/16571/" target="_blank" User
    = ", usado no site, é de criação de "
    a href="http://www.thenounproject.com/ofcapl" target="_blank" OfcaPL
    = " e publicado originalmente no "
    a href="http://www.thenounproject.com" target="_blank" The Noun Project
    = " sob lincensa "
    a href="http://creativecommons.org/licenses/by/3.0/us/" target="_blank" Creative Commons – Attribution (CC BY 3.0)